easy_admin:
    site_name: "Administration"
    design:
        brand_color: '#33cc33'
    entities:
        Image:
            class: App\Entity\Image
        Ingredient:
            class: App\Entity\Ingredient
        Recipe:
            class: App\Entity\Recipe
