easy_admin:
    site_name: "Administration"
    design:
        brand_color: '#33cc33'
    entities:
        Recipe:
            class: App\Entity\Recipe
            label: Rezepte
            form: # applies to both new and edit
                title: 'Rezept hinzufügen'
            new:
            edit:
                title: 'Rezept ändern'
        Ingredient:
            class: App\Entity\Ingredient
            label: Zutaten
        Image:
            class: App\Entity\Image
            label: Bilder
