easy_admin:
    site_name: "Administration"
    design:
        brand_color: '#009900'
    entities:
        Recipe:
            class: App\Entity\Recipe
            label: Rezepte
            list:
                title: Rezepte
                fields:
                    - id
                    - { property: 'title', label: 'Titel' }
                    - { property: 'ingredients', label: 'Zutaten' }
                    - { property: 'images', label: 'Bilder' }
            form: # applies to both new and edit
                title: 'Rezept hinzufügen'
                fields:
                    - id
                    - { property: 'title', label: 'Titel' }
                    - { property: 'instructions', label: 'Zubereitung', type: 'Hillrange\CKEditor\Form\CKEditorType' }
                    - { property: 'ingredients', label: 'Zutaten' }
                    - { property: 'images', label: 'Bilder' }
            new:
            edit:
                title: 'Rezept ändern'
        Ingredient:
            class: App\Entity\Ingredient
            label: Zutaten
        Image:
            class: App\Entity\Image
            label: Bilder
