easy_admin:
    site_name: "Administration"
    design:
        brand_color: '#009900'
    formats:
        datetime: 'd.m.Y H:i e'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '', title: 'ändern' }
            - { name: 'delete', icon: 'trash', label: '', title: 'löschen' }
    entities:
        Recipe:
            class: App\Entity\Recipe
            label: Rezepte
            search:
                sort: ['title', 'ASC']
            list:
                sort: ['title', 'ASC']
                title: Rezepte
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'ingredients', label: 'Zutaten' }
                    - { property: 'images', label: 'Bilder' }
                    - { property: 'meal', label: 'Gang', type: 'string', template: 'EasyAdmin/field_meal.html.twig'}
                    - { property: 'updated', label: 'zuletzt geändert', type: 'datetime' }
                    - { property: 'created', label: 'erstellt', type: 'datetime' }
            form: # applies to both new and edit
                title: 'Rezept hinzufügen'
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'instructions', label: 'Zubereitung', type: 'Hillrange\CKEditor\Form\CKEditorType' }
                    - { property: 'ingredients', label: 'Zutaten' }
                    - { property: 'images', label: 'Bilder' }
                    - { property: 'meal', label: 'Gang'}
            new:
            edit:
                title: 'Rezept ändern'
        Ingredient:
            class: App\Entity\Ingredient
            label: Zutaten
            search:
                sort: ['name', 'ASC']
            list:
                sort: ['name', 'ASC']
                title: Zutaten
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'recipes', label: 'Rezepte' }
                    - { property: 'updated', label: 'zuletzt geändert', type: 'datetime' }
                    - { property: 'created', label: 'erstellt', type: 'datetime' }
            form:
                title: 'Zutat hinzufügen'
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'description', label: 'Beschreibung', type: 'Hillrange\CKEditor\Form\CKEditorType' }
                    - { property: 'link', label: 'Link' }
                    - { property: 'recipes', label: 'Rezepte' }
        Image:
            class: App\Entity\Image
            label: Bilder
