#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#aws_cognito_login:
#    path: /login
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#    defaults:
#        path: https://davidweichert.auth.eu-central-1.amazoncognito.com/login?response_type=code&client_id=6b6hohnk0onerq1cndj6bottt0&redirect_uri=https://kochrezepte.davidweichert.de/login
###            https://davidweichert.auth.eu-central-1.amazoncognito.com/login?response_type=code&client_id=6b6hohnk0onerq1cndj6bottt0&redirect_uri=https://kochrezepte.davidweichert.de/callback&scope=06bfa83c06cfa466c016cfc95ab7178c
#        permanent: true
